### ISSUE TITLE
Pulling most popular purchased item

### ISSUE THREAD

**Issue by thkro** [rsanchez/activerecord#1]
Trying to use the code below to grab the most popular purchased item from my cart throb purchased items channel but only shows titles alphabetically. Any ideas of what I may be doing wrong? Thanks!

{exp:activerecord select="title, COUNT(title) AS score" from="channel_titles" where:channel_id="9" group_by="title" sort_by="score desc"}
 <li>{title}</li>
{/exp:activerecord}

**Comment by rsanchez** [comment]
sort_by isn't a param, you've got order_by and sort, so:

```
{exp:activerecord select="title, COUNT(title) AS score" from="channel_titles" where:channel_id="9" group_by="title" order_by="score" sort="desc"}
```

**Comment by thkro** [comment]
Thanks! Works great. Not sure if you can guide me in the right direction with the next question... I am able to pull the url title but need to grab the full page url as defined in my structure tab. Any ideas on how to do this?

**Comment by rsanchez** [comment]
I've never used structure before, so I can't be too sure, but I know that the regular pages module stores the full page url in kind of a wacky place. It's not easily accessible to query/activerecord and you might have to use some PHP: http://expressionengine.com/forums/viewreply/841068/

**Comment by thkro** [comment]
Yeah, I've been struggling to locate the full url. Will have a look at the article and do some more testing. Thanks for your help!
