### ISSUE TITLE
member_id and userdata

### ISSUE THREAD

**Issue by GDmac** [rsanchez/activerecord#2]
Grmbl, memberdata is parsed late in the template parsing process. 
Making it difficult to fetch profile fields for the current user.

Added the following in build_query 

```
foreach ($params as $method => $value)
{
    // some normally late parsed variables that are already in the session
    if($value=="{member_id}") $value = $this->EE->session->userdata['member_id'];
```

**Comment by rsanchez** [comment]
Added a fix for this.

**Comment by GDmac** [comment]
Man you're way to quick, or did you had it laying around already?

**Comment by rsanchez** [comment]
no, just quick :)
