### ISSUE TITLE
*ignore* parsing of stash tags when passed within query params

### ISSUE THREAD

**Issue by MattLGBrown** [rsanchez/activerecord#3]
Please ignore - my mistake!

---

Following not working (not parsing stash tag variable)

{exp:activerecord 
select="author_id, title"
distinct="yes"
from="channel_titles"
where="channel_id = 15"
where_in:author_id="{exp:stash:get name='stash_product_authors'}"}

**Comment by rsanchez** [comment]
You should add parse="inward" to the activerecord tag. Or wrap the whole activerecord tag in a exp:stash:parse tag, and use {stash:stash_product_authors} as your where_in:author_id param;
