### ISSUE TITLE
Excerpts

### ISSUE THREAD

**Issue by brianpeddle** [rsanchez/activerecord#4]
I have tried to use a variety of Excerpt plugins on the results and they all get ignored .. one example one http://devot-ee.com/add-ons/excerpt1

{exp:excerpt limit="5"}{description}{/exp:excerpt}

It will just output the full description.  Is there anything in this plugin that would prevent tags being used like this?

Thanks!

**Comment by rsanchez** [comment]
Yep, try adding parse="inward" to the activerecord tag.

**Comment by brianpeddle** [comment]
Grrr. I apologize, I did that but thats what I get for cut and pasting that, it had non utf-8 quotes.  Once I fixed it worked.  Thank You.

**Comment by rsanchez** [comment]
No apology necessary. Glad to help!
