### ISSUE TITLE
Is there a way to handle multiple joins?

### ISSUE THREAD

**Issue by stevegrossi** [rsanchez/activerecord#5]
I've tried

```
join[a]="channel_data"
...
join[b]="relationships"
```

Thinking it might work like `where`, but this doesn't do any of the joins. I've also tried

```
join="channel_data"
...
join="relationships"
```

But this only does the last join.

**Comment by rsanchez** [comment]
There isn't way to do it, mostly because join depends on other parameters, on and join_type.

**Comment by stevegrossi** [comment]
Got it. Thanks for the quick reply, and a great plugin!

**Comment by rsanchez** [comment]
Just pushed a new version with an updated join syntax, which allows you to do multiple joins.

```
join:channel_data="channel_data.entry_id = channel_titles.entry_id"
join:relationships="relationships.parent_id = channel_titles.entry_id"
```
