### ISSUE TITLE
no_results is not working.

### ISSUE THREAD

**Issue by Stephenwny** [rsanchez/activerecord#6]
Hello,

I do not know if i am doing something wrong or it is the plugin. I set this query up so it will return no records so i can test the no_results. When i run it, my web page is blank. Here is the code;
{exp:activerecord
    select="channel_titles.title AS title,
            channel_titles.url_title AS article_link,
            channel_data.field_id_6 AS authors,
            channel_data.field_id_7 AS conference,
            channel_data.field_id_8 AS keywords,
            channel_data.field_id_10 AS file,
            channel_data.field_id_16 AS article_type,
            channel_data.field_id_19 AS external_link,
            channel_data.field_id_15 AS publication,
            channel_data.field_id_21 AS year,
            channel_data.field_id_17 AS volume,
            channel_data.field_id_13 AS issue,
            channel_data.field_id_14 AS pages"
    protect_select="yes"
    from="channel_titles"
    left_join:channel_data="channel_data.entry_id = channel_titles.entry_id"
    where:channel_data.channel_id = "7"
    limit="15"
    paginate="both"

}
    {!-- this parses exactly like a query module tag --}

```
{if no_results}<h3>We're sorry, but we couldn't find anything for you. Please try another search.</h3>{/if}

    {title}<br />
    {article_link}<br />
    {authors}<br />
    {conference}<br />
    {keywords}<br />
    {file}<br />
    {article_type}<br />
    {external_link}<br />
    {publication}<br />
    {year}<br />
    {volume}<br />
    {issue}<br />
    {pages}<br /><br />
    {paginate}
    <p>Page {current_page} of {total_pages} pages {pagination_links}</p>
    {/paginate}
```

{/exp:activerecord}

Since there is no id of 7 here, where:channel_data.channel_id = "7", I should get no records back and trigger the no_results if statement but it does not. I just get a blank page.

Regards,
Stephen

**Comment by rsanchez** [comment]
Are you nested inside another plugin tag? Sometimes that can interfere with a no_results tag. Otherwise I’d suggest turning on debugging info and looking for the SQL query that the module generates. Copy that query over to your SQL client and see what the results look like.

**Comment by Stephenwny** [comment]
I did try the sql in phpmyadmin, it returned zero rows.
I am upgrading our companies web site (which I did not build), it is possible that it is nested inside another plugin. I will turn on debugging info, check for the nested plugin, and get back to you with what I find tomorrow.

**Comment by rsanchez** [comment]
Can you grab the latest from the master branch? I think this solves it.

**Comment by Stephenwny** [comment]
It works, you rock!

Thank you
Stephen
