### ISSUE TITLE
Parse a hash

### ISSUE THREAD

**Issue by colinambler** [rsanchez/activerecord#8]
Hey Ron,

I'm wondering if there's a way to parse an array / hash.  I'm working with VZ Address field, with my goal to separate the output as individual fields.  Sample:

`{"street":"583 King of Prussia Rd","street_2":"","city":"Radnor","region":"PA","postal_code":"19087","country":"US"}`

**Comment by rsanchez** [comment]
There isn't a way built into activerecord. You'll probably have to get at that string via PHP (either with a plugin or with PHP enabled templates) and `json_decode` it.
